### PR TITLE
Improvement  corrects urls

### PR DESCRIPTION
**Pull request by ChatLurking**

### CODE REVIEW

**Comment by balthazar** [comment]
Nice, thanks for this! I guess now that the `/user` endpoint is available it would be possible to fully use passport for it? I might throw a diff this weekend for this.

What's this new `response_type`?

**Comment by ChatLurking** [comment]
The `/user` endpoint would be possible to use passport for.

`response_type` is required for just `/authorize` the docs say that it is used to tell the api to return an auth token.

**Comment by balthazar** [comment]
That's cool!

Don't you think having the response_type being `code` by default instead of requiring people to specify it themselves would be better? Since it will only be used for web apps anyway so it should be fine. If you could make that change and removing the readme one it would be perfect.

**Comment by balthazar** [comment]
Great! Thanks again

**Pull request merged**
